add launch file demo_mode
tue-robotics/amigo_bringup pull request #68
Opened 2017-10-07 09:35 UTC by MatthijsBurgh

2017-10-07 09:59 UTC, jlunenburg commented
I added a concise README and comments referring to this in the launch file to clarify which of the three demo launch files to use in which situation.

@reinzor as the maintainer of this package: could you review this pull request?

2017-10-07 10:07 UTC, LoyVanBeek requested changes

2017-10-07 10:07 UTC, LoyVanBeek commented on launch/state_machines/README.md
> +* free_mode.launch: this launches ED with localization. Therefore, it entirely depends on the environment in which this is used.
What does this mean? Can I use this in a random place or on in a known place?

2017-10-07 12:53 UTC, jlunenburg commented on launch/state_machines/demo_mode.launch
> +<?xml version="1.0"?>
Maybe demo_extern is more consistent

2017-10-12 11:59 UTC, MatthijsBurgh commented
@LoyVanBeek please review again.

2017-10-12 12:03 UTC, LoyVanBeek approved these changes

2017-10-12 12:16 UTC, MatthijsBurgh commented
@Rayman Do you agree with  b0c4004?

2017-10-17 20:29 UTC, merged