add "or true" to alias generation
tue-robotics/amigo_bringup pull request #88
Opened 2017-12-19 21:49 UTC by MatthijsBurgh

2017-12-20 11:59 UTC, Rayman requested changes

2017-12-20 11:59 UTC, Rayman commented on env-hooks/99.amigo_functions.bash
> +        eval "${name}() { export ROBOT_BRINGUP_PATH=${package_path} && rosnode kill /state_machine || true && roslaunch ${launch_file} \$@; }"
Just use a `;`

2017-12-21 09:56 UTC, Rayman commented
Did you test this?

2017-12-21 10:11 UTC, MatthijsBurgh commented
Yep, it works and solves the problem

2017-12-21 13:18 UTC, Rayman approved these changes

2017-12-21 13:18 UTC, merged